
# node js (nvm)
install-nvm:
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
	. ~/.nvm/nvm.sh && nvm install --lts

# npm global
install-npm:
	npm i -g yarn 
	npm i -g pnpm 
	npm i -g @vue/cli 
	npm i -g @nestjs/cli 
	npm i -g express-generator
	npm i -g pnpm
	npm i -g bun 
	npm i -g ts
	npm i -g ts-node

install: install-nvm install-npm
	
	
