all: install-nvm install-npm

# node js (nvm)
install-nvm:
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
	. ~/.nvm/nvm.sh && nvm install --lts

# npm global
install-npm:
	npm i yarn -g
	npm i pnpm -g
	npm i @vue/cli -g
	npm i @nestjs/cli -g
	npm i express-generator -g
	npm i pnpm -g
	npm i bun -g
	npm i ts -g
	npm i ts-node -g


	
	
